" alexs neato vimrc 

" originally, this vimrc was distilled from other sites. however,
" it has grown into its present state through several years of 
" perl, shell and sql development on unix. it has suited me
" fairly well, and should be a good starting point for 
" developers new to vim. however! i have not tested this on 
" windows, nor do i intend to, and i will freely admit to
" having a strong disgust for the windows 'operating' system.

" So, the original sources of some of this are here:

" http://www.cip.biologie.uni-osnabrueck.de/niehaus/linux/howtos/img/vimrc
" http://vim.sourceforge.net/tips/tip.php?tip_id=156
" http://metacosm.dhs.org/
" http://www.csclub.uwaterloo.ca/u/mvcorks/vim/vimrc
" http://sites.netscape.net/bbenjif/vim/_vimrc
" http://www.naglenet.org/vim/syntax/_vimrc
" http://www.leonid.maks.net/writings/vim-for-perl-dev/vim-for-perl-dev.html

" $Revision: 1.4 $
" $Date: 2004-02-23 18:56:45 $

" this sets up some non-sucky syntax coloring. dark blue on black
" is super hard to read. (not used anymore, we're using koehler
" highlight perlComment ctermfg=white
" highlight perlComment ctermbg=blue
" highlight rubyComment ctermfg=white
" highlight rubyComment ctermbg=blue
" highlight vimComment ctermfg=white
" highlight vimComment ctermbg=blue

" this turns syntax on. duh.
syntax on

" hopefully this is here. we like this color scheme.
colo koehler

set nocompatible
set autoindent
set number
set tabstop=2
set showmatch
set mat=2
set showmode
set nohlsearch
set foldenable
set foldmethod=marker
set backspace=indent,eol,start
set backup
set backupdir=~/.vim/backup
set directory=~/.vim/tmp
set history=1024
set ruler
set hid
set viminfo='20,\"50
set backspace=2 whichwrap+=<,>,h,l
set nocindent
set cmdheight=2
set comments=b:#,b:\",n:>
set ignorecase
set magic
set showmode

" this will probably upset most people.
set list 
set listchars=tab:\|\ " note trailing space

" fix these perl typos
ab prnt print
ab wran warn
ab prnit print

" i use this to make sure my code looks the way i 
" wrote it in my editor. you may not like my tabs
" and the fact that they're two spaces. however,
" my code will look fine with this, and you can go
" and change your settings yourself.
"
" if you must blame something for this, blame perl
" hackers. that's what everyone else does.
ab mystamp # aja // vim:tw=80:ts=2:noet

" substitute these typos for what I DWIM'd
cabbrev Wq wq
cabbrev Prel perl
cabbrev prel perl
cabbrev Perl perl
cabbrev pelr perl
cabbrev peerl perl
cabbrev zsg zsh

" like :wq except write and suspend
command Wst w <bar> st
cabbrev wst Wst

" add a nifty macro
ab ubp #!/usr/bin/perl
ab uws use warnings;use strict;
ab mkh my ($kernel, $heap) = (@_[ KERNEL, HEAP ]);

" this puts our search term in the middle of the screen
nmap n nmzz.`z
nmap N Nmzz.`z
nmap * *mzz.`z
nmap # #mzz.`z
nmap g* g*mzz.`z
nmap g# g#mzz.`z

" limit text files to 78 chars
autocmd BufRead *.txt set textwidth=78

" we stole this from matt, but its so cool!

" vim
" List of words from Microsoft Word 7, with some additions
" Author: Matt Corks <mvcorks@alumni.uwaterloo.ca>
ab accesories accessories
ab accomodate accommodate
ab acheive achieve
ab acheiving achieving
ab acn can
ab acommodate accommodate
ab acomodate accommodate
ab adn and
ab agian again
ab ahppen happen
ab ahve have
ab allready already
ab almsot almost
ab alot a lot
ab alreayd already
ab alwasy always
ab amke make
ab anbd and
ab andthe and the
ab appeares appears
ab aplyed applied
ab artical article
ab audeince audience
ab audiance audience
ab awya away
ab bakc back
ab balence balance
ab baout about
ab bcak back
ab beacuse because
ab becasue because
ab becomeing becoming
ab becuase because
ab becuse because
ab befoer before
ab begining beginning
ab beleive believe
ab boxs boxes
ab bve be
ab changeing changing
ab charachter character
ab charecter character
ab charector character
ab cheif chief
ab circut circuit
ab claer clear
ab claerly clearly
ab cna can
ab colection collection
ab comany company
ab comapny company
ab comittee committee
ab commitee committee
ab committe committee
ab committy committee
ab compair compare
ab compleated completed
ab completly completely
ab comunicate communicate
ab comunity community
ab conected connected
ab cotten cotton
ab coudl could
ab cpoy copy
ab cxan can
ab danceing dancing
ab definately definitely
ab develope develop
ab developement development
ab differant different
ab differnt different
ab diffrent different
ab disatisfied dissatisfied
ab doese does
ab doign doing
ab doller dollars
ab donig doing
ab driveing driving
ab drnik drink
ab ehr her
ab embarass embarrass
ab equippment equipment
ab esle else
ab excitment excitement
ab eyt yet
ab familar familiar
ab feild field
ab fianlly finally
ab fidn find
ab firts first
ab follwo follow
ab follwoing following
ab foriegn foreign
ab fro for
ab foudn found
ab foward forward
ab freind friend
ab frmo from
ab fwe few
ab gerat great
ab geting getting
ab giveing giving
ab goign going
ab gonig going
ab govenment government
ab gruop group
ab grwo grow
ab haev have
ab happend happened
ab haveing having
ab hda had
ab helpfull helpful
ab herat heart
ab hge he
ab hismelf himself
ab hsa has
ab hsi his
ab hte the
ab htere there
ab htey they
ab hting thing
ab htink think
ab htis this
ab hvae have
ab hvaing having
ab idae idea
ab idaes ideas
ab ihs his
ab immediatly immediately
ab indecate indicate
ab insted intead
ab inthe in the
ab iwll will
ab iwth with
ab jsut just
ab knwo know
ab knwos knows
ab konw know
ab konws knows
ab levle level
ab libary library
ab librarry library
ab librery library
ab librarry library
ab liek like
ab liekd liked
ab liev live
ab likly likely
ab littel little
ab liuke like
ab liveing living
ab loev love
ab lonly lonely
ab makeing making
ab mkae make
ab mkaes makes
ab mkaing making
ab moeny money
ab mroe more
ab mysefl myself
ab myu my
ab neccessary necessary
ab necesary necessary
ab nkow know
ab nwe new
ab nwo now
ab ocasion occasion
ab occassion occasion
ab occurence occurrence
ab occurrance occurrence
ab ocur occur
ab oging going
ab ohter other
ab omre more
ab onyl only
ab optoin option
ab optoins options
ab opperation operation
ab orginized organized
ab otehr other
ab otu out
ab owrk work
ab peopel people
ab perhasp perhaps
ab perhpas perhaps
ab pleasent pleasant
ab poeple people
ab porblem problem
ab probelm problem
ab protoge protege
ab puting putting
ab pwoer power
ab quater quarter
ab questoin question
ab reccomend recommend
ab reccommend recommend
ab receieve receive
ab recieve receive
ab recieved received
ab recipie recipe
ab recipies recipes
ab recomend recommend
ab reconize recognize
ab recrod record
ab religous religious
ab rwite write
ab rythm rhythm
ab seh she
ab selectoin selection
ab sentance sentence
ab seperate separate
ab shineing shining
ab shiped shipped
ab shoudl should
ab similiar similar
ab smae same
ab smoe some
ab soem some
ab sohw show
ab soudn sound
ab soudns sounds
ab statment statement
ab stnad stand
ab stopry story
ab stoyr story
ab stpo stop
ab strentgh strength
ab struggel struggle
ab sucess success
ab swiming swimming
ab tahn than
ab taht that
ab talekd talked
ab tath that
ab teh the
ab tehy they
ab tghe the
ab thansk thanks
ab themselfs themselves
ab theri their
ab thgat that
ab thge the
ab thier their
ab thme them
ab thna than
ab thne then
ab thnig thing
ab thnigs things
ab thsi this
ab thsoe those
ab thta that
ab tihs this
ab timne time
ab tje the
ab tjhe the
ab tkae take
ab tkaes takes
ab tkaing taking
ab tlaking talking
ab todya today
ab tongiht tonight
ab tonihgt tonight
ab towrad toward
ab truely truly
ab tyhat that
ab tyhe the
ab useing using
ab veyr very
ab vrey very
ab waht what
ab watn want
ab wehn when
ab whcih which
ab whic which
ab whihc which
ab whta what
ab wief wife
ab wierd weird
ab wihch which
ab wiht with
ab windoes windows
ab withe with
ab wiull will
ab wnat want
ab wnated wanted
ab wnats wants
ab woh who
ab wohle whole
ab wokr work
ab woudl would
ab wriet write
ab wrod word
ab wroking working
ab wtih with
ab wya way
ab yera year
ab yeras years
ab ytou you
ab yuo you
ab yuor your
" Days of weeks
ab monday Monday
ab tuesday Tuesday
ab wednesday Wednesday
ab thursday Thursday
ab friday Friday
ab saturday Saturday
ab sunday Sunday
" Canadian spellings
ab colour color
ab honor honour
" Other
ab xmas christmas
ab Xmas Christmas
