#!/usr/bin/perl -w

BEGIN { $|++; $ENV{ACCOUNT} ? print "1..5\n" : ( print "1..0\n" and exit ); }
END   { print "not ok 1 # modules did not load\n" unless $looks_good }

use strict;
use warnings;
use vars qw/$looks_good/;
$looks_good=1;
print "ok 1\n";

my ( $wizard, $items );

my $i = 2;

###
test ( eval { require Neopets::Shops::Wizard } ? 1 : 0, $i++ );
test ( eval { require Neopets::Item::Simple } ? 1 : 0, $i++ );
test ( $wizard = Neopets::Shops::Wizard -> new(), $i++ );
test ( $items = $wizard -> search(
    { item => Neopets::Item::Simple -> new(
        { name => 'Palm Fan' } ),
      exact => 1, max_price => 1 } ), $i++ );

exit;

sub test {
  print $_[0] ? "" : "not ",
        "ok $_[1]",
        $_[2] ? " $_[2]" : "", "\n";
}
