#!/usr/bin/perl -w

BEGIN { $|++; print "1..3\n"; }
END   { print "not ok 1 # modules did not load\n" unless $looks_good }

use strict;
use warnings;
use vars qw/$looks_good/;
$looks_good=1;
print "ok 1\n";

my $i = 2;

###
test ( 1, $i++ );
test ( 0, $i++, "# comment" );

exit;

sub test {
  print $_[0] ? "" : "not ",
        "ok $_[1]",
        $_[2] ? " $_[2]" : "", "\n";
}
